### ISSUE TITLE
What happened to my edits?

### ISSUE THREAD

**Issue by jliermann** [ComPlat/chemotion_saurus#108]
I made some additions to https://www.chemotion.net/chemotionsaurus/docs/eln/settings (Pullrequests [85](https://github.com/ComPlat/chemotion_saurus/pull/85) and [73](https://github.com/ComPlat/chemotion_saurus/pull/73)) but these changes seem to be gone. Also, there are now two files `/master/docs/eln/configuration.md` and `/master/docs/eln/configuration.mdx`.

**Comment by PiTrem** [comment]
@Allenskywalker92 Can you check. was it lost with the versioning?

**Comment by PiTrem** [comment]
so the file had been renamed (configuration.md -> configuration.mdx) some time ago, but the previous version (.md) got somehow resurrected and had precedence over the .mdx one.

**Comment by jliermann** [comment]
Thanks! :)
