### ISSUE TITLE
Versioning for ELN docs

### ISSUE THREAD

**Issue by Ira-Maier** [ComPlat/chemotion_saurus#15]
Versioning of the ELN documentation is available:
Current version 0.9: https://www.chemotion.net/chemotionsaurus/docs/eln/videos_eln 
Old version 0.8: https://www.chemotion.net/chemotionsaurus/docs/eln/version-0.8/videos_eln

**Comment by JanCBrammer** [comment]
https://docusaurus.io/docs/versioning

**Comment by JanCBrammer** [comment]
Transferred to #127
