### ISSUE TITLE
Populate empty landing page

### ISSUE THREAD

**Issue by JanCBrammer** [ComPlat/chemotion_saurus#150]
As remarked by users at RWTH, the landing page (rendered at https://www.chemotion.net/docs/ and configured at https://github.com/ComPlat/chemotion_saurus/blob/b3bc2d0cecc5e2bfb13fc051551e67749e52d62f/docs/index.mdxt) is currently empty.

@nicolejung, do you have suggestions for content?

**Comment by harivyasi** [comment]
Thanks @lemondi93 for fixing this :)
