### ISSUE TITLE
Rework Sidebar

### ISSUE THREAD

**Issue by harivyasi** [ComPlat/chemotion_saurus#171]
As suggested by @nicolejung, the sidebar can be more intuitive, especially for the `repo` section. This issue tracks the progress in this direction.

**Comment by harivyasi** [comment]
@phuang26 if you approve the PR #172 then the above layout will be accepted.

I am still working on decorative separator lines in the sidebar.

**Comment by phuang26** [comment]
Hi Shashank,

Thanks for your work. The following points are the result of our discussion via Discord last Friday:
1. please keep the "author" information 
2. please use the wording from Nicole's e-mail, e.g. "Details and Standards"...etc.

I think that's pretty much everything. Once you commit your changes, I can review them again and approve them.

Thank you.
