### ISSUE TITLE
Fix deploy job CI.

### ISSUE THREAD

**Issue by JanCBrammer** [ComPlat/chemotion_saurus#62]
The deploy job fails intermittently with: 
```bash
kex_exchange_identification: read: Connection reset by peer
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: unexplained error (code 255) at io.c(235) [sender=3.1.3]
Error: Process completed with exit code 255.
```

**Comment by PiTrem** [comment]
done

**Comment by JanCBrammer** [comment]
@PiTrem, could you have a look?

**Comment by harivyasi** [comment]
Further improvements were made to CI workflow with https://github.com/ComPlat/chemotion_saurus/commit/8265777e6aa3b207ef02060906496e590513ae9f and https://github.com/ComPlat/chemotion_saurus/commit/e0e03a13857069803591b25e2201ca46aec49b70. Maybe we close this now.
